train: true
fine_tune_type: lora
optimizer: adamw
mask_prompt: true
num_layers: -1
batch_size: 1
iters: 120
val_batches: 12
learning_rate: 0.00001
steps_per_report: 20
steps_per_eval: 20
save_every: 40
max_seq_length: 4096
grad_accumulation_steps: 2
clear_cache_threshold: 17179869184
seed: 20260825
lora_parameters:
  rank: 16
  dropout: 0.0
  scale: 32.0
