#!/usr/bin/env python3
"""Create the reviewed-property seed for the UI catalog adaptation ledger.

The source contract is generated by ``extract_json_render_contracts.mjs`` from
the pinned upstream checkout. This script is intentionally a seed generator:
it establishes one explicit disposition record for every source prop, event,
and child slot while keeping all readiness states PENDING. It must not be used
to overwrite later hand-reviewed evidence without reviewing the resulting diff.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys


DEFAULT_CONTRACT = Path("tooling/deal-ui-pack/vercel-json-render-contract-v1.json")
DEFAULT_LEDGER = Path("tooling/deal-ui-pack/vercel-ui-coverage-v2.json")
DEFAULT_GALLERY = Path("app/src/debug/assets/ui-catalog/manifest.json")
DEFAULT_OUTPUT = Path("tooling/deal-ui-pack/vercel-ui-adaptations-v1.json")
PACK_PATH = Path("tooling/deal-ui-pack/deal-studio-v16.dealui-pack")
PACK_MANIFEST_PATH = Path("tooling/deal-ui-pack/deal-studio-v16.agent.json")


# Each source contract has one intentional native representation. ``planned``
# means the representation is a named delivery target, not an implementation
# claim. A property is never implicitly covered merely because this row exists.
TARGETS: dict[tuple[str, str], tuple[str, str, str]] = {
    ("shadcn", "Card"): ("Card", "active", "mobile card surface"),
    ("shadcn", "Stack"): ("Flex", "active", "flex layout adapter"),
    ("shadcn", "Grid"): ("Grid", "active", "adaptive grid adapter"),
    ("shadcn", "Separator"): ("Divider", "active", "divider adapter"),
    ("shadcn", "Tabs"): ("Tabs", "active", "tabs plus TabItem recipe"),
    ("shadcn", "Accordion"): ("Accordion", "planned", "accordion recipe"),
    ("shadcn", "Collapsible"): ("Collapsible", "planned", "disclosure recipe"),
    ("shadcn", "Dialog"): ("Dialog", "active", "modal dialog adapter"),
    ("shadcn", "Drawer"): ("BottomSheet", "active", "bottom-sheet adapter"),
    ("shadcn", "Carousel"): ("Carousel", "planned", "horizontal carousel recipe"),
    ("shadcn", "Table"): ("DataTable", "planned", "typed data-table recipe"),
    ("shadcn", "Heading"): ("Heading", "active", "heading adapter"),
    ("shadcn", "Text"): ("Text", "active", "text variant adapter"),
    ("shadcn", "Image"): ("Image", "active", "image adapter"),
    ("shadcn", "Avatar"): ("Avatar", "active", "avatar adapter"),
    ("shadcn", "Badge"): ("Badge", "active", "badge variant adapter"),
    ("shadcn", "Alert"): ("InsetBanner", "active", "semantic alert adapter"),
    ("shadcn", "Progress"): ("NumberProgressBar", "active", "numeric progress adapter"),
    ("shadcn", "Skeleton"): ("Skeleton", "active", "loading skeleton adapter"),
    ("shadcn", "Spinner"): ("Spinner", "active", "loading spinner adapter"),
    ("shadcn", "Tooltip"): ("Tooltip", "planned", "touch-accessible help presentation"),
    ("shadcn", "Popover"): ("Popover", "planned", "touch popover presentation"),
    ("shadcn", "Input"): ("TextField", "active", "typed text-field adapter"),
    ("shadcn", "Textarea"): ("TextArea", "active", "multiline text adapter"),
    ("shadcn", "Select"): ("Select", "active", "typed select recipe"),
    ("shadcn", "Checkbox"): ("Checkbox", "active", "boolean field adapter"),
    ("shadcn", "Radio"): ("RadioGroup", "active", "single-choice recipe"),
    ("shadcn", "Switch"): ("Toggle", "active", "boolean switch adapter"),
    ("shadcn", "Slider"): ("NumberSlider", "active", "fractional slider adapter"),
    ("shadcn", "Button"): ("Button", "active", "button adapter"),
    ("shadcn", "Link"): ("Link", "planned", "permission-aware URL action"),
    ("shadcn", "DropdownMenu"): ("Menu", "active", "menu plus MenuItem recipe"),
    ("shadcn", "Toggle"): ("ToggleButton", "active", "toggle-button adapter"),
    ("shadcn", "ToggleGroup"): ("ToggleGroup", "planned", "single-or-multiple toggle recipe"),
    ("shadcn", "ButtonGroup"): ("SegmentedControl", "active", "segmented button-group adapter"),
    ("shadcn", "Pagination"): ("Pagination", "planned", "pagination control"),
    ("react-native", "Container"): ("Flex", "active", "surface/flex adapter"),
    ("react-native", "Row"): ("Flex", "active", "horizontal flex adapter"),
    ("react-native", "Column"): ("Flex", "active", "vertical flex adapter"),
    ("react-native", "ScrollContainer"): ("Scroll", "active", "scroll adapter"),
    ("react-native", "SafeArea"): ("SafeArea", "planned", "host-inset recipe"),
    ("react-native", "Spacer"): ("Spacer", "active", "spacing adapter"),
    ("react-native", "Pressable"): ("Pressable", "active", "press and long-press adapter"),
    ("react-native", "Divider"): ("Divider", "active", "divider adapter"),
    ("react-native", "Heading"): ("Heading", "active", "heading adapter"),
    ("react-native", "Paragraph"): ("Text", "active", "paragraph text adapter"),
    ("react-native", "Label"): ("Text", "active", "field-label text adapter"),
    ("react-native", "Image"): ("Image", "active", "image adapter"),
    ("react-native", "Avatar"): ("Avatar", "active", "avatar adapter"),
    ("react-native", "Badge"): ("Badge", "active", "badge status adapter"),
    ("react-native", "Chip"): ("Chip", "planned", "selectable/removable chip"),
    ("react-native", "Button"): ("Button", "active", "button adapter"),
    ("react-native", "TextInput"): ("TextField", "active", "text input adapter"),
    ("react-native", "Switch"): ("Toggle", "active", "boolean switch adapter"),
    ("react-native", "Checkbox"): ("Checkbox", "active", "boolean checkbox adapter"),
    ("react-native", "Slider"): ("NumberSlider", "active", "fractional slider adapter"),
    ("react-native", "SearchBar"): ("TextField", "active", "search text-field recipe"),
    ("react-native", "Spinner"): ("Spinner", "active", "loading spinner adapter"),
    ("react-native", "ProgressBar"): ("NumberProgressBar", "active", "fractional progress adapter"),
    ("react-native", "Card"): ("Card", "active", "card surface adapter"),
    ("react-native", "ListItem"): ("ListItem", "active", "list-item adapter"),
    ("react-native", "Modal"): ("Modal", "active", "modal overlay adapter"),
    ("jev-playground", "Metric"): ("Stat", "active", "metric/stat adapter"),
    ("jev-playground", "BarGraph"): ("BarChart", "active", "labelled bar-chart adapter"),
}


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def pack_components(path: Path) -> set[str]:
    return set(re.findall(r"^export component ([A-Za-z][A-Za-z0-9_]*)\(", path.read_text(encoding="utf-8"), re.M))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--contract", type=Path, default=DEFAULT_CONTRACT)
    parser.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER)
    parser.add_argument("--gallery", type=Path, default=DEFAULT_GALLERY)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    contract = read_json(args.contract)
    ledger = read_json(args.ledger)
    gallery = read_json(args.gallery)
    if contract.get("schemaVersion") != "deal-studio-json-render-contract-extraction-v1":
        raise ValueError("unsupported upstream contract schema")
    if ledger.get("schemaVersion") != 1:
        raise ValueError("unsupported coverage ledger schema")
    if gallery.get("schemaVersion") != "deal-studio-ui-catalog-fixtures-v1":
        raise ValueError("unsupported gallery fixture schema")
    if not PACK_PATH.is_file() or not PACK_MANIFEST_PATH.is_file():
        raise ValueError("active v16 pack source or manifest is missing")

    source_pairs = {
        (origin, name)
        for origin, catalog in contract["components"].items()
        for name in catalog
    }
    ledger_pairs = {(row["origin"], row["name"]) for row in ledger["rows"]}
    if source_pairs != ledger_pairs:
        missing = sorted(ledger_pairs - source_pairs)
        extra = sorted(source_pairs - ledger_pairs)
        raise ValueError(f"source/ledger denominator mismatch; missing={missing}, extra={extra}")
    if set(TARGETS) != ledger_pairs:
        missing = sorted(ledger_pairs - set(TARGETS))
        extra = sorted(set(TARGETS) - ledger_pairs)
        raise ValueError(f"target map must cover exactly the ledger; missing={missing}, extra={extra}")

    active_components = pack_components(PACK_PATH)
    pack_manifest = read_json(PACK_MANIFEST_PATH)
    if pack_manifest.get("packVersion") != "deal-studio-dealui-pack-v16":
        raise ValueError("expected the v16 pack manifest")
    fixture_ids: dict[tuple[str, str], list[str]] = {}
    for case in gallery["cases"]:
        fixture_ids.setdefault((case["origin"], case["component"]), []).append(case["id"])

    rows = []
    for ledger_row in ledger["rows"]:
        origin, name = ledger_row["origin"], ledger_row["name"]
        source = contract["components"][origin][name]
        component, availability, summary = TARGETS[(origin, name)]
        if availability == "active" and component not in active_components:
            raise ValueError(f"active target {origin}.{name} -> {component} is absent from the v16 pack")
        rows.append(
            {
                "origin": origin,
                "component": name,
                "status": "PENDING",
                "target": {
                    "component": component,
                    "availability": availability,
                    "summary": summary,
                },
                "properties": {
                    prop: {"state": "PENDING", "targetProperty": None}
                    for prop in sorted(source["props"])
                },
                "events": {
                    event: {"state": "PENDING", "targetEvent": None}
                    for event in source["events"]
                },
                "slots": {
                    "source": source["slots"],
                    "state": "PENDING",
                    "targetSlot": None,
                },
                "fixtureIds": sorted(fixture_ids.get((origin, name), [])),
                "evidence": {
                    "contractCompile": "PENDING",
                    "interactive": "PENDING",
                    "visual": "PENDING",
                    "accessibility": "PENDING",
                },
            }
        )

    result = {
        "schemaVersion": "deal-studio-ui-adaptation-v1",
        "sourceContract": {
            "path": str(args.contract),
            "sha256": sha256(args.contract),
        },
        "targetPack": {
            "version": pack_manifest["packVersion"],
            "sourcePath": str(PACK_PATH),
            "sha256": sha256(PACK_PATH),
        },
        "requiredRows": len(rows),
        "rows": rows,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {args.output} with {len(rows)} source-component adaptations")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"UI catalog adaptation seed failed: {error}", file=sys.stderr)
        raise SystemExit(1)
